// ---------------------------------------------------------------------------
// PIXEL ART ENGINE
//
// Sprites are plain character grids. Each character maps to a slot in a
// palette, so one shape can be recoloured per species.
//
//   O outline   S shadow (back)   D dorsal    B body     M midtone/dither
//   L belly     H highlight       F fin       A accent
//   E eye white P pupil           . transparent
//
// The M slot is what does the work: dithering M against B and L gives a soft
// gradient down the flank without needing more colours, which is what makes
// these read as shaded rather than flat.
//
// Fish bodies are hand-drawn and their caudal fins generated as an outlined
// forked tail — see tools/author_sprites.py, which emits the block below.
// Edit sprites THERE and regenerate, rather than hand-editing these grids.
// ---------------------------------------------------------------------------

export const SPRITES = {
  deep: [
    '..........OOOOOOOO........OFO',
    '.........OFFFFFFFO........OFO',
    '........OFFFFFFFFFO......OFO.',
    '......OOOFFFFFFFFOOO....OFFO.',
    '....OOSSSOOOOOOOOSSSOO..OFFO.',
    '...OSSSSSSSSSSSSSSSSSO.OFFFO.',
    '..OSSSSSDDDDDDDDDDDDSOOFFFO..',
    '.OSDDDDDDDDBBBBBBBBBDOOFFFO..',
    'OODDDDDBBBBBBBBBBBBBBOFFFFO..',
    'OEPEODDBBBBBBMBMBBBBBOFFFO...',
    'OEEEOBBBBBMBMBMBMBBBBOFFFO...',
    'OOEEOBBMBMBMBMBMBMBBBOFFFO...',
    '.OOMMMMLMLMLMLMLMLMLBOFFFFO..',
    '..OMLLLLLLLLLLLLLLLMBOOFFFO..',
    '..OLLLLLLLLLLLLLLLLLBOOFFFO..',
    '..OHLLLLLLLLLLLLLLLLOO.OFFFO.',
    '..OHHLLLLLLLLLLLLLLOO...OFFO.',
    '...OOHHLLLLLLLLLLOO.....OFFO.',
    '.....OOOFFFFFFOOO........OFO.',
    '.......OFFFFFFO...........OFO',
    '.......OOOOOOOO...........OFO',
  ],
  perch: [
    '............OOOOOOOOO.........OFO',
    '...........OFFFFFFFFO........OFFO',
    '..........OFFFFFFFFFFO.......OFO.',
    '.......OOOOFFFFFFFFFOOO.....OFFO.',
    '....OOOSSSSOOOOOOOOSSSSOO..OFFFO.',
    '..OOSSSSSSSSSSSSSSSSSSSSO.OFFFO..',
    '.OSSSSSSDDDDDDDDDDDDDDDSOOFFFFO..',
    'OODDDDDDDDDDBBBBBBBBBBBDOFFFFO...',
    'OEPEODDDDBBBBBBBBBBBBBBBOFFFFO...',
    'OEEEOBBBBBBBBMBMBMBBBBBBOFFFO....',
    'OOEEOBBBBMBMBMBMBMBMBBBBOFFFFO...',
    '.OOMMMBMBMBMBMBMBMBMBMBBOFFFFO...',
    '..OMMLMLMLMLMLMLMLMLMLMBOOFFFFO..',
    '..OLLLLLLLLLLLLLLLLLLLLBO.OFFFO..',
    '...OHLLLLLLLLLLLLLLLLLLOO..OFFFO.',
    '...OOHHLLLLLLLLLLLLLLLOO....OFFO.',
    '.....OOOFFOOOOFFFFOOOO.......OFO.',
    '.......OFFO...OFFFO..........OFFO',
    '.......OOOO...OOOO............OFO',
  ],
  torpedo: [
    '................OOOO.............OFO',
    '...............OFFFFO...........OFFO',
    '..............OFFFFFO..........OFFO.',
    '........OOOOOOOFFFFOOOO.......OFFFO.',
    '.....OOOSSSSSSSSSSSSSSSOO....OFFFO..',
    '...OOSSSSSSSSSSSSSSSSSSSSO..OFFFFO..',
    '.OOSSDDDDDDDDDDDDDDDDDDDDSOOFFFFO...',
    'OODDDDDDDDDBBBBBBBBBBBBBBDOFFFFFO...',
    'OEPEODDDBBBBBBBBBBBBBBBBBBOFFFFO....',
    'OEEEOBBBBBBMBMBMBMBMBBBBBBOFFFFO....',
    'OOEEOBBMBMBMBMBMBMBMBMBMBBOFFFFFO...',
    '.OOMMMLMLMLMLMLMLMLMLMLMLBOOFFFFO...',
    '..OLLLLLLLLLLLLLLLLLLLLLLBO.OFFFFO..',
    '...OOHLLLLLLLLLLLLLLLLLLLOO..OFFFO..',
    '.....OOOHHLLLLLLLLLLLLLLOO....OFFFO.',
    '........OOOOOFFOOOFFOOOOO......OFFO.',
    '.............OFFO.OFFO..........OFFO',
    '..............OO...OO............OFO',
  ],
  tuna: [
    '...........OOOO....................OFO',
    '..........OFFFFO..................OFFO',
    '.........OFFFFFFO................OFFO.',
    '........OFFFFFFFFO..............OFFFO.',
    '.....OOOOFFFFFFFFOOOO.........OOFFFO..',
    '...OOSSSSOOOOOOOOSSSSSOO.....OFFFFFO..',
    '.OOSSSSSSSSSSSSSSSSSSSSSOO..OFFFFFO...',
    'OODDDDDDDDDDDDDDDDDDDDDDDSOOFFFFFFO...',
    'OEPEODDDDDBBBBBBBBBBBBBBBDAOFFFFFO....',
    'OEEEOBBBBBBBBBBMBMBMBBBBBBAOFFFFO.....',
    'OOEEOBBBBBMBMBMBMBMBMBBBBBAOFFFFFO....',
    '.OOMMMMBMBMBMBMBMBMBMBMBMBAOFFFFFFO...',
    '..OMLLLLLLLLLLLLLLLLLLLLLLBOOFFFFFO...',
    '..OLLLLLLLLLLLLLLLLLLLLLLLOO.OFFFFFO..',
    '..OOHLLLLLLLLLLLLLLLLLLLLAO...OOFFFO..',
    '...OOOHHLLLLLLLLLLLLLLLLAO......OFFFO.',
    '.....OOOOFFFFFOOOOOOOOOO.........OFFO.',
    '........OFFFFFFO..................OFFO',
    '.........OOOOOO....................OFO',
  ],
  grouper: [
    '..........OOOOOOOOOOO.......OFO',
    '.........OFFFFFFFFFFFO......OFO',
    '.......OOOFFFFFFFFFFFFO....OFO.',
    '....OOOSSSOOOOOOOOOOOOOO...OFO.',
    '..OOSSSSSSASSSSASSSSSSSSO.OFFO.',
    '.OSSSSSSSSSSSSSSSSSSSSSDOOFFFO.',
    'OODDDADDDDDDDDADDDDDDDDDOOFFO..',
    'OEPEODDDBBBBABBBBBBBABBBOFFFO..',
    'OEEEOBBBBBBBBBBBABBBBBBBOFFFO..',
    'OOEEOBBABBBBMBMBMBBBABMBOFFFO..',
    '.OOMMMBBBBMBMBMBMBMBMBMBOFFFO..',
    '..OMMLMLALMLMLMLMLALMLMBOOFFO..',
    '..OLLLLLLLLLLLLALLLLLLLBOOFFFO.',
    '..OHLLLLLLLLLLLLLLLLLLLOO.OFFO.',
    '..OOHHLLLLLLLLLLLLLLLLOO...OFO.',
    '....OOOFFFFOOOOFFFFFOOO....OFO.',
    '......OFFFFO..OFFFFFO.......OFO',
    '......OOOOOO..OOOOOO........OFO',
  ],
  long: [
    '..............OOOOOO..............OFO',
    '.............OFFFFFO.............OFO.',
    '..........OOOOFFFFOOOOO.........OFFO.',
    '...OOOOOOOSSSSOOOOSSSSSSOO.....OFFFO.',
    '.OOSSSSSSSSSSSSSSSSSSSSSSSSO..OFFFO..',
    'OODDDDDDDDDDDDDDDDDDDDDDDDDSOOFFFFO..',
    'OEPEODDDDBBBBBBBBBBBBBBBBBBDOFFFFO...',
    'OEEEOBBBBBBBBBBBBBBBBBBBBBBBOFFFO....',
    'OOEEOBMBMBMBMBMBMBMBMBMBMBMBOFFFFO...',
    '.OOMMMLLLLLLLLLLLLLLLLLLLLLBOOFFFFO..',
    '..OLLLLLLLLLLLLLLLLLLLLLLLLOO.OFFFO..',
    '..OOHLLLLLLLLLLLLLLLLLLLLLOO...OFFFO.',
    '....OOOOFFOOOOOOOOFFFOOOOO......OFFO.',
    '.......OFFO......OFFO............OFO.',
    '.......OOOO......OOOO.............OFO',
  ],
  oval: [
    '......A.A.A.A.A.A.A.........OFO',
    '......OAOAOAOAOAOAO.........OFO',
    '.....OOFFFFFFFFFFFOO.......OFO.',
    '...OOOFFFFFFFFFFFFFOOO....OFFO.',
    '..OOSSSOOOOOOOOOOOOSSSOO.OFFFO.',
    '.OSSSSSSSSSSSSSSSSSSSSSO.OFFO..',
    '.OSSSSSDDDDDDDDDDDDDDDDOOFFFO..',
    'OODDDDDDDBBBBBBBBBBBBBBOFFFFO..',
    'OEPEODDDBBBBBBMBMBBBBBBOFFFO...',
    'OEEEOBBBBBMBMBMBMBMBBBBOFFFO...',
    'OOEEOBBMBMBMBMBMBMBMBMBOFFFO...',
    '.OOMMMMLMLMLMLMLMLMLMLBOFFFFO..',
    '..OMLLLLLLLLLLLLLLLLLLBOOFFFO..',
    '..OLLLLLLLLLLLLLLLLLLLBO.OFFO..',
    '..OHLLLLLLLLLLLLLLLLLLOO.OFFFO.',
    '..OOHHLLLLLLLLLLLLLLLOO...OFFO.',
    '....OOOFFFFFFFFFFFFOO......OFO.',
    '......OFFFFFFFFFFOO.........OFO',
    '......OOOOOOOOOOOO..........OFO',
  ],
  forked: [
    '..........OOOOOOO...............OFO',
    '.........OFFFFFFFO.............OFFO',
    '........OFFFFFFFFFO..........OOFFO.',
    '......OOOFFFFFFFFOOO........OFFFFO.',
    '...OOOSSSOOOOOOOOSSSSOO....OFFFFO..',
    '.OOSSSSSSSSSSSSSSSSSSSSO.OOFFFFFO..',
    'OOSSSSDDDDDDDDDDDDDDDDSOOFFFFFFO...',
    'OODDDDDDDDBBBBBBBBBBBBDOFFFFFFO....',
    'OEPEODDDBBBBBBBMBMBBBBBOFFFFFO.....',
    'OEEEOBBBBBBMBMBMBMBMBBBOFFFFFO.....',
    'OOEEOBBMBMBMBMBMBMBMBMBOFFFFFO.....',
    '.OOMMMMLMLMLMLMLMLMLMLBOFFFFFFO....',
    '..OMLLLLLLLLLLLLLLLLLLBOOFFFFFFO...',
    '..OLLLLLLLLLLLLLLLLLLLOO.OOFFFFFO..',
    '..OOHLLLLLLLLLLLLLLLLOO....OFFFFO..',
    '...OOOHHLLLLLLLLLLLLOO......OFFFFO.',
    '.....OOOOFFFOOOOOOOO.........OOFFO.',
    '........OFFFFO.................OFFO',
    '........OOOOOO..................OFO',
  ],
  squid: [
    '........OOOOOO.....',
    '......OOSSAASSOO...',
    '.....OSSAAAAAASO...',
    '....OSSAAAAAAAASO..',
    '...OSBBBBBBBBBBBSO.',
    '...OBBBBBBBBBBBBBO.',
    '..OBBBEPBBBBBBEPBBO',
    '..OBBBEEBBBBBBEEBBO',
    '..OBBBBBBBBBBBBBBBO',
    '..OBMBMBMBMBMBMBMBO',
    '...OMMMMMMMMMMMMMO.',
    '...OLOLOLOLOLOLOLO.',
    '...OL.OL.OL.OL.OLO.',
    '..OL..O...O...O..LO',
    '..O...O...O...O...O',
  ],
  crab: [
    '...OO.............OO...',
    '..OAAO..OOOOOOO..OAAO..',
    '..OAAOOOSSSSSSSOOOAAO..',
    '...OOOSSEPSSSEPSSOOO...',
    '....OSBBBBBBBBBBBBSO...',
    '...OSBBBBBBBBBBBBBBSO..',
    '..OOBBBBBBBBBBBBBBBBOO.',
    '.O.OOBBBBMBMBMBMBBBOO.O',
    '.O..OOMMMMMMMMMMMMOO..O',
    '..O..O.OOOOOOOOOO.O..O.',
    '..O..O..O......O..O..O.',
    '.....O..O......O..O....',
  ],
};

// Icon sprites (non-species) used for section headers and empty states.
export const ICONS = {
  // Weather icons are drawn in tools/author_sprites.py and regenerated from
  // there — do not hand-edit. Render them with the 'weather' palette, which
  // carries five cloud tones (S..H) plus two golds (F rim, A core) so clouds
  // read with depth and the sun has an edge rather than being a flat blob.
  sunny: [
    '.........FF.........',
    '...F.....FF.....F...',
    '....F..........F....',
    '.......FFFFFF.......',
    '.....FFAAAAAAFF.....',
    '....FAAAHHHAAAAF....',
    '...FAAAHHHHHAAAAF...',
    '...FAAHHHHHAAAAAF...',
    'FF.FAAAHHHAAAAAAF.FF',
    '...FAAAAAAAAAAAAF...',
    '...FAAAAAAAAAAAAF...',
    '....FAAAAAAAAAAF....',
    '.....FFAAAAAAFF.....',
    '.......FFFFFF.......',
    '....F..........F....',
    '...F.....FF.....F...',
    '.........FF.........',
  ],
  moon: [
    '.........FFFFF......',
    '..F....FFAAAAAF.....',
    '......FFAAAAAF......',
    '.....FFAAAAF........',
    '.....FAAAAF.........',
    '.F...FAAAAF.........',
    '.....FAAAAF.........',
    '.....FFAAAAF........',
    '......FFAAAAAF......',
    '.......FFAAAAAF.....',
    '.........FFFFF......',
  ],
  cloudy: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOLHHHHHHHHHLOO...',
    '.OLLLHHHHHHHHHLLLO..',
    '.OMLLLLHHHHHLLLLMO..',
    '.OBMMLLLLLLLLLMMBO..',
    '.ODBBMMMMMMMMMBBDO..',
    '.OSDDBBBBBBBBBDDSO..',
    '..OOSSSSSSSSSSSOO...',
  ],
  partly: [
    '..............FAA...',
    '...........FFAAAAAF.',
    '..........FAAAHHAAF.',
    '....OOOO..FAAAHHAAF.',
    '..OOHHHHOOFAAAAAAAF.',
    '.OLHHHHHHHOFAAAAAF..',
    '.OMLLHHHHHHOFFFFF...',
    '.OBMMLLLLLLLO.......',
    '.ODBBMMMMMMMBO......',
    '.OSDDBBBBBBBDSO.....',
    '..OOSSSSSSSSSOO.....',
  ],
  drizzle: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOLHHHHHHHHHLOO...',
    '.OLLLHHHHHHHHHLLLO..',
    '.OMLLLLHHHHHLLLLMO..',
    '.OBMMLLLLLLLLLMMBO..',
    '.ODBBMMMMMMMMMBBDO..',
    '..OOSSSSSSSSSSSOO...',
    '....................',
    '....D...D...D.......',
    '....................',
    '...D...D...D........',
  ],
  rain: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOLHHHHHHHHHLOO...',
    '.OLLLHHHHHHHHHLLLO..',
    '.OMLLLLHHHHHLLLLMO..',
    '.OBMMLLLLLLLLLMMBO..',
    '.ODBBMMMMMMMMMBBDO..',
    '..OOSSSSSSSSSSSOO...',
    '....................',
    '...D...D...D...D....',
    '...D...D...D...D....',
    '....................',
    '..D...D...D...D.....',
    '..D...D...D...D.....',
  ],
  showers: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOLHHHHHHHHHLOO...',
    '.OLLLHHHHHHHHHLLLO..',
    '.OMLLLLHHHHHLLLLMO..',
    '.OBMMLLLLLLLLLMMBO..',
    '.ODBBMMMMMMMMMBBDO..',
    '..OOSSSSSSSSSSSOO...',
    '....................',
    '..D..D..D..D..D.....',
    '.D..D..D..D..D......',
    '..D..D..D..D..D.....',
    '.D..D..D..D..D......',
  ],
  storm: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOLHHHHHHHHHLOO...',
    '.OLLLHHHHHHHHHLLLO..',
    '.OMLLLLHHHHHLLLLMO..',
    '.OBMMLLLLLLLLLMMBO..',
    '.ODBBMMMMMMMMMBBDO..',
    '..OOSSSSSSSSSSSOO...',
    '..........FAAAF.....',
    '.........FAAAF......',
    '........FAAAF.......',
    '......FAAAAAAAF.....',
    '.........FAAF.......',
    '........FAAF........',
    '........FAF.........',
  ],
  fog: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOLHHHHHHHHHLOO...',
    '.OLLLHHHHHHHHHLLLO..',
    '.OMLLLLHHHHHLLLLMO..',
    '.OBMMLLLLLLLLLMMBO..',
    '..OOSSSSSSSSSSSOO...',
    '....................',
    '..MMMMMMMMMMMMMM....',
    '....................',
    '.MMMMMMMMMMMMMM.....',
    '....................',
    '..MMMMMMMMMMMM......',
  ],
  wave: [
    '.............LLLLLLLL.........',
    '..........LLLLLLLLLLLLLLL.....',
    '........LLLLLLLLLLLLLLLLLLLL..',
    '.......LLLLLLLLL.......MLLLLLL',
    '......LMMMMMMM...........MLLLL',
    '.....LMMBBBBB.............MLLL',
    '....LMBBBBBB..............MLLL',
    '....LMBBBBB..............MLLL.',
    '...LMBBBBBB.............MLLL..',
    '...LMBBBBBB............MLLL...',
    '..LMBBBBBBD..........MLLLL....',
    '..LMBBBBBDD.......MMLLLL......',
    '.LMBBBBBDDDD..MMMLLLL.........',
    '.LMBBBBDDDDDMMLLLLL...........',
    'LMBBBBDDDDDDDLLLL.............',
    'LMBBBDDDDDDDDDD...............',
    'MBBBDDDDDDDDDDDDDDDDDDDDDDDDDD',
    'BDDDDDDDDSSSSSSSSSSSSSSSSSSSSS',
    'DDSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
  ],
  hook: [
    '.........AAAA..',
    '........AA..AA.',
    '.......AA....AA',
    '.......AA....AA',
    '........AA..AA.',
    '.........AAAA..',
    '..........AA...',
    '..........AA...',
    '..........AA...',
    '..........AA...',
    '..........AA...',
    '..........AA...',
    '..........AA...',
    '...A......AA...',
    '...AA.....AA...',
    '...AAA....AA...',
    '...A.AA...AA...',
    '...A......AA...',
    '...AA.....AA...',
    '....AA...AA....',
    '.....AA.AA.....',
    '......AAA......',
  ],
  trophy: [
    '...BBBBBBBBBB.....',
    '..BOOOOOOOOOOB....',
    '.BMOLLLLLLLLOMB...',
    '.BMOLMMMMMMLOMB...',
    '.BMOMMMMMMMMOMB...',
    '..BOMMMMMMMMOB....',
    '...BOMMMMMMOB.....',
    '....BOMMMMOB......',
    '.....BBMMBB.......',
    '.......BB.........',
    '.....BBBBBB.......',
    '...BBBBBBBBBB.....',
  ],
  boat: [
    '.............AA...........',
    '.............AAAA.........',
    '.............AA...........',
    '.............SS...........',
    '........SSSSSSSSSS........',
    '.......SLLLLLLLLLLS.......',
    '.......SSSSSSSSSSSS.......',
    '...SSSSSSSSSSSSSSSSSSSS...',
    '...SS....SBBBBBBS....SS...',
    '..SBBS...SBBBBBBS...SBBS..',
    '..SBBS...SBBBBBBS...SBBS..',
    '..SSSS....SBBBBS....SSSS..',
    '...SS......SSSS......SS...',
    '..........................',
    'MMLLMMLLMMLLMMLLMMLLMMLLMM',
  ],
  book: [
    '..OOOOOOOOOOOOOO..',
    '..OBBBBBBOBBBBBO..',
    '..OBLLLLBOBLLLLO..',
    '..OBLLLLBOBLLLLO..',
    '..OBBBBBBOBBBBBO..',
    '..OBLLLLBOBLLLLO..',
    '..OBLLLLBOBLLLLO..',
    '..OBBBBBBOBBBBBO..',
    '..OOOOOOOOOOOOOO..',
  ],
};

// Large angled art for the species detail sheet only.
// Generated by tools/author_sprites.py: each horizontal sprite is
// mirrored, supersampled, rotated ~32 degrees with nearest-neighbour
// sampling so pixels stay hard, then majority-downsampled and re-outlined.
// Nose up-right, tail down-left. Do not hand-edit — regenerate instead.
export const HEROES = {
  snapper: [
    '............................OOOOO..........',
    '.........................O.OOSSSSOO........',
    '.......................OOOOSSSSSSOOO.......',
    '................OOOOOOOOSSSSSDDDDOOO.......',
    '...............OSFSFFFSSSSDDDDDOOEEOO......',
    '.............OOFSSFFSSSSDDDDDDDOEEEEOO.....',
    '...........OOFFSFFSSSSSDDDDDBBDOEPPEOO.....',
    '..........OOFSFFSSSSSDDDDDBBBBBOEPEEOO.....',
    '........OOFSFFFSSSSDDDDDBDBBBBBOOEEOOO.....',
    '........OSSFFSSSSSDDDDBDBBBBBMMMBMMMMO.....',
    '.........OSSSSSSDDDDDBBDBBBBMMBMMMMLMO.....',
    '..........OSSSSDDDDBBDBBHHMMBBMMMMMMMLO....',
    '.OO.......ODDDDDDBDDBBBBMMMBMBMMMMMLLLOO...',
    'OFFOOOO....ODDDDBBDBBBBMMBMBMMMMMLLLLLOO...',
    '.OOFFFFOO..OODBBDBBBBMMBMMBMMMLLLLLLHHO....',
    '...OFFFFOOOOODDBBBBBMMBMBMMMMMLLLLLLLO.....',
    '...OOFFFFFFFOOBBBBMMBMBMMMMMLLLLLLLFO......',
    '.....OFFFFFFFOBBMMBMBMMMMLLLLLLLLLSSFO.....',
    '......OOFFFFFFOMMMMBMMMLLLLLLLLLOOFSO......',
    '.......OOFFFFFFOBBMMMMLLLLLLLLOO..OO.......',
    '........OFFFFFFOBBMMLLMLLLLLLFO............',
    '.........OOFFFFOOBLMLLLLLLLFFFO............',
    '..........OFFFFOOOBLLLLLLLFFSOO............',
    '..........OFFFFO.OBLLLLLFSSOO..............',
    '...........OFFFO..OOOLOOOOOO...............',
    '..........OFFFFO...OOO.....................',
    '...........OFFFO...........................',
    '...........OFFFO...........................',
    '...........OFFO............................',
    '...........OOFO............................',
    '............OFO............................',
    '............OFO............................',
    '............OFO............................',
    '.............O.............................',
  ],
  barracuda: [
    '....................................OOO.......',
    '.................................O.OSSSOO.....',
    '...............................OOSOSSSSOO.....',
    '........................OOOOOOOSSSSDDDDEEO....',
    '......................OOSFFOSSSSDDDDBDEPEO....',
    '.....................OSFSSSSSSDDDDBDDOPEEOO...',
    '....................OFFSSSSSDDDDBDDBMOOEOO....',
    '.....................OOSSSSDDDDDBDMMBMOOOO....',
    '....................OSSSSDDDDDDDBMMMMMMLLO....',
    '...................OSSSSDDDBDBBMMBMMMLLLLO....',
    '..................OSSSDDDDDBBMMBMMMMLLLHO.....',
    '...............OOOOSDDDDDDDBMMMMMMLMLLLOO.....',
    '.............OOFSSSDDDDDDBMMMMMMLMLLLLOO......',
    '............OFSSSDDDDDBBBMMMBMMLLLLLFOO.......',
    '............OFSSDDDDBBBMMMBMMLMLLLLFSFO.......',
    '............OSDDDDDBBDMMMMMLMLLLLOOFSOO.......',
    '.O..........ODDDDBBDMMMBMMMLLLLOO..OO.........',
    'OFOOOO......ODDBDBMMMBMMMMLLLLOO..............',
    'OOFFFFOOOOOODDBBDMMBMMLMLLLLOO................',
    '.OOFFFFFFFFOOBDMMMBMMMLLLLLO..................',
    '...OOFFFFFFFOOMMBMMMMLLLLFOO..................',
    '.....OOFFFFFFOBMMMMLLLLLFSFO..................',
    '......OOOFFFFFOBMLLLLLFSFOO...................',
    '........OFFFFOOBOLLLOOFFOO....................',
    '........OFFFFO.OOOLO..OO......................',
    '........OOFFFO....O...........................',
    '.........OFFFO................................',
    '.........OFFO.................................',
    '.........OFFO.................................',
    '.........OFFO.................................',
    '.........OFO..................................',
    '.........OFO..................................',
    '.........OO...................................',
  ],
  jack: [
    '..............................O.O.........',
    '...........................O.OSOOOO.......',
    '.....................O.OOOOSOSSSSSO.......',
    '..................OOOOOSOSSSSSSDSOOO......',
    '................OOFSSFSSSSSDDDDDDEOO......',
    '...............OFSFFSSSSSSDDDDDDEPPEO.....',
    '.............OOSSFSSSSSSDDDDDBOOEPPEO.....',
    '............OSSSFSSSSSSDDDDDDBBOEEEEO.....',
    '............OFFSSSSSSDDDDDBBBBBMOEOOOO....',
    '...........OFSSSSSSDDDDDBDBBBMMBBOOMO.....',
    '............OSSSSSDDDDBBBBHBMMBMBMMMMO....',
    '............OSSSDDDDDBBDBBMMBMBMMMMMLO....',
    '............OSSDDDDBDDBBMMBMBMMMMLLLLO....',
    '.OOOO.......ODDDDBBDBBBMMMMBMMMLLLLLHO....',
    'OFFFFOOOO...ODDDBBDBBMMBMBMMMMMLLLLLOO....',
    '.OFFFFFFFOOOOOBDDBBMMBMBMMMMLLLLLLFOO.....',
    '..OOFFFFFFFFFODBBBMMMBBMMMLMLLLLLSFFO.....',
    '...OOFFFFFFFFFOBMMMMBMMMLMLLLLLOOFSOO.....',
    '.....OFFFFFFFFOOMMBMMMMLLMLLLLOOOOO.......',
    '......OOFFFFFFFOBMMMMLLMLLLLFO............',
    '........OOOFFFFFOBMLLMLLLLLFFO............',
    '..........OFFFFFOOBLMLLLLFSSFO............',
    '..........OFFFFFOOBLLLLFSSFOO.............',
    '..........OFFFFO..OOOLOOOOO...............',
    '..........OFFFFO....OO....................',
    '..........OFFFFO..........................',
    '..........OFFFFO..........................',
    '..........OFFFO...........................',
    '..........OFFFO...........................',
    '...........OFFO...........................',
    '...........OFFO...........................',
    '...........OFO............................',
    '...........OO.............................',
  ],
  mullet: [
    '...............................O.OO........',
    '.............................OOSOSSOO......',
    '......................OOOOOOOSSSSDSOOO.....',
    '....................OOSFFOSSSSDDDDDEEO.....',
    '...................OOFFFSSSSDDDDBDEEEEO....',
    '...................OFFSSSSSDDDDDDDEPEEO....',
    '...................OOSSSSDDDDDDDBOEEOOO....',
    '..................OSSSSDDDDBDDBBBMOOOOO....',
    '.................OSSSSDDDDDBDBBMMBMMMMO....',
    '..............OOOOSSDDDDDDDBBHMMBMMMLLLO...',
    '.............OOFFSSDDDDDDBBBMMBMMMLLLOO....',
    '...........OOSFSSDDDDDBBBBMMBMMMMLLLHO.....',
    '...........OFSSDDDDDBDBBBMMMMMMLLLLLOO.....',
    '...........OSSDDDDDDBBBMMBMMMLLLLLLOO......',
    '.O.........ODDDDDBBBBBMBMMMMLLLLLSSFO......',
    'OFOOOO.....ODDDBBBBBMMMMMMLMLLLOOFSOO......',
    'OOFFFFOOOOOODBDBBBMMMMMMLMLLLLOOOOO........',
    '.OOFFFFFFFFFOBDBBMMMBMMLLLLLOO.............',
    '...OOFFFFFFFOOBMMMBMMLMLLLLO...............',
    '.....OFFFFFFFOMMMMMLMLLLLSFO...............',
    '.....OOOOFFFFFOBMMMLLLLSFSSOO..............',
    '........OFFFFFOBBMLLLLFFSOO................',
    '.........OFFFFOOOLLLOOOFOO.................',
    '.........OFFFO.OOOOO...O...................',
    '.........OFFFO.............................',
    '........OOFFFO.............................',
    '.........OFFFO.............................',
    '.........OFFO..............................',
    '.........OFFO..............................',
    '..........OFO..............................',
    '.........OFFO..............................',
    '..........OO...............................',
  ],
  catfish: [
    '..............................OO.........',
    '.............................OAAO........',
    '.............................OAAO........',
    '.............................OAAOO.......',
    '.............................OAOOSOOO....',
    '.............................OOSSSSEO....',
    '........................OOOOOOSDDSEEEO...',
    '......................OOSSSSSSDDOEPEEO...',
    '.....................OOSSSSSDDDDOEEEOO...',
    '...................OOSFSSSSDDBBBOOOOAAO..',
    '.................OOOFSSSSDDBBBDMMMMMAAO..',
    '................OOFSSSSDDDBBDMMMMMMOAO...',
    '..............OOSFSSSSDDBDDMMMMMMMMOAO...',
    '.............OOFSSSSDDBDDDMMMBMMMLLOO....',
    '...........OOFSSSSSDDBBDMMMMMMMLLLFOO....',
    '..........OOFSSSSDDBDDBMMMMMMLLLSFOO.....',
    '.........OFSSSSDDBDDDMMMBMMLLLLFOO.......',
    '........OOSSSSDDDDDMMMBMMMLLLFFOO........',
    '.O......OSSSDDDDDBMMBMMMLLLLFOO..........',
    'OFOO....OSSDDDBBMMMBMMLLLLFSOO...........',
    '.OOFOOOOODDDBBMMMBMMMLLLFSOO.............',
    '..OOFFFOODDBBMMMMMMLMLLFOO...............',
    '...OFFFFFOBMMMBMMLMLLFSOO................',
    '....OOFFFOOMBMMMLLLFSOO..................',
    '.....OOOFFOBBMLMLLSOOO...................',
    '......OFFFOOBMLLFSOO.....................',
    '.......OFFOOOOLSOO.......................',
    '......OFFFO.OOFOO........................',
    '.......OFFO...O..........................',
    '.......OFFO..............................',
    '........OO...............................',
    '........OFO..............................',
    '........OO...............................',
  ],
  deep: [
    '...............OOOO..O.OOO..........',
    '.............OOFFFFOOSOSSSOO........',
    '............OOFFFFFOSSSSSDDOOO......',
    '..........OOFFFFFFOSSSSDDDDPEOO.....',
    '..........OFFFFFOOSSDDDDDDEEEOO.....',
    '..........OFFFFOSSDDDDBBDDOEEOO.....',
    '..........OOOOOSSDDDDBBBBBBOMO......',
    '..........OSSSSDDBBBBBBBBBMMMMO.....',
    '.OO......OSSSSDBBBBBBMBBMMMLLLO.....',
    'OFOOO....OSSDDBBBBMBBMBMMLLLLLHO....',
    '.OFFFOO..OSDBBBBMBBBBMMLLLLLLHHO....',
    '..OOFFOOOOODBBBBMBBMMLLLLLLLLHO.....',
    '...OFFFFFOOBBBBBMMMMLLLLLLLLHHO.....',
    '....OFFFFFFOBBBBMMLLLLLLLLLLOO......',
    '.....OOFFFFOOBBMLLLLLLLLLLLFO.......',
    '......OOFFFFOBLMLLLLLLLLLFFFOO......',
    '........OFFFFOBMLLLLLLLFFFFOO.......',
    '.........OFFFOOBLLLLLLOFFFO.........',
    '........OFFFFOOOOOOOOOOOOO..........',
    '.........OFFFO..O.O....O............',
    '.........OOFFO......................',
    '.........OFFO.......................',
    '.........OOFFO......................',
    '..........OFFO......................',
    '...........OO.......................',
    '..........OFOO......................',
    '...........OFO......................',
  ],
  perch: [
    '..........................OOOOO.......',
    '.................OOO..OOOOSSSSOOO.....',
    '...............OOFFFOOOSSSSSDDPEO.....',
    '..............OFFFFFFSSSSSSDDEEEOO....',
    '............OOFFFFFOOSSDDDDDDOEEO.....',
    '...........OFFFFFFOOSSDDDDDBBOOMO.....',
    '...........OFFFFOOSSDDDDBBBBBMMMO.....',
    '...........OFFFOOSDDBBBBBBBBBMMMLO....',
    '...........OOSSSSDDBBBBBBMBBLMLLOO....',
    '..........OSSSSDDBBBBMBBMBMMLLLLOO....',
    '.OOO......OSSSDDBBBBMBMBMMLLLLLHO.....',
    'OFFFO....OOSDDBBBBMBMBMLMLLLLLLOO.....',
    '.OFFFOOOO.OSDBBBBBMMBMMLLLLLLFOO......',
    '..OOFFFFFOOODBBBBMBMMLLLLLLLFFFO......',
    '...OFFFFFFFOOBBBBMMMLLLLLLOOOFOO......',
    '....OOFFFFFFOBBBMMLLLLLLLO..OO........',
    '......OOFFFFFOBBLLLLLLLFFO............',
    '.......OOFFFFOBBLLLLLLFFFO............',
    '........OFFFFOOBLLLLOOFOO.............',
    '.........OFFFOOOOOOO..OO..............',
    '........OFFFFO........................',
    '.........OFFO.........................',
    '.........OFFO.........................',
    '.........OFFO.........................',
    '.........OOFO.........................',
    '..........OFO.........................',
    '.........OOFO.........................',
    '..........OO..........................',
  ],
  torpedo: [
    '...............................OO.......',
    '.........................O.OOOOSOOO.....',
    '........................OSOSSDSDDEEO....',
    '................OOO...OOSSSSDDDDEEEO....',
    '...............OOFFOOOSSSSDDDDDOEEEO....',
    '..............OFFFFFOSSSDDDDDDBBOEOO....',
    '..............OFFFFSSSSDDDDBBBBBMMLO....',
    '..............OOOSSSSDDBBBBBBMMLMLO.....',
    '..............OOSSSSDBBBBBMBMLMLLHO.....',
    '.............OSSSSDDBBBBMBMLLLLLLO......',
    '.............OSSDDBBBBMBMMLMLLLLO.......',
    '............OSSDDBBBBBBMLMLLLLHHO.......',
    '.OOOO.......ODDBBBBMBMBMLLLLLLOO........',
    'OFFFFOOOO..OSDBBBBBMBMLLLLLLLO..........',
    '.OFFFFFFFOOOODBBBBMLMLLLLLLFO...........',
    '..OOFFFFFFFFOBBBMBMLLLLLLOFFO...........',
    '....OOFFFFFFFOBBMLLLLLLLOOFO............',
    '......OFFFFFFOOBLLLLLLFFOOOO............',
    '.......OOFFFFOOBLLLLLOFFO...............',
    '........OFFFFO.OOOLOOOFO................',
    '........OFFFFO..OOO...O.................',
    '.........OFFFO..........................',
    '........OFFFO...........................',
    '.........OFFO...........................',
    '.........OFFO...........................',
    '.........OFO............................',
    '.........OFO............................',
    '.........OFO............................',
    '..........O.............................',
  ],
  tuna: [
    '......................OO......O.O.O.......',
    '.....................OOFOOO.OOSOSOOOO.....',
    '....................OFFFFFFOOSSSDDPEO.....',
    '...................OFFFFFFFOSSSDDEEEOO....',
    '...................OFFFFFOOSSDDDDOEEOO....',
    '...................OFFFFOOSSDDDBBOOMO.....',
    '...................OFFOOSSDDDDBBBBMMOO....',
    '...................OOOOSDDBBBBBBBMLLLO....',
    '.................OOSSSSDDBBBBBBMLLLLOO....',
    '................OSSSSDDBBBBMBMBLLLLLOO....',
    '...............OSSSSDDBBMMBMBLLLLLLOO.....',
    '...............OSSDDBBMBBMMBLLLLLLHOO.....',
    '..............OSDDBBMBBBMBLLLLLLLLO.......',
    '.OOOO.........ODDBBBBBMBLLLLLLLLFFO.......',
    'OFFFFOOOOOOO.OSDBBBBMBBLLLLLLLFFFFO.......',
    '.OOFFFFFFFFFOOABBBBBBLLLLLLLLFFFOO........',
    '...OOFFFFFFFFOAABBBMLLLLLLLOOFFOO.........',
    '....OOFFFFFFFFOABMLLLLLLLOO.OOO...........',
    '......OFFFFFFFOOBLLLLLLLOO................',
    '.......OOOFFFFFOOLLLLLOO..................',
    '.........OFFFFFOOOAALOO...................',
    '.........OFFFFO...OOO.....................',
    '.........OFFFFO...........................',
    '.........OFFFO............................',
    '.........OFFFO............................',
    '.........OFFO.............................',
    '.........OFFO.............................',
    '.........OOFO.............................',
    '.........OFFO.............................',
    '..........OFO.............................',
  ],
  grouper: [
    '........................OOOO........',
    '.................OOO.OOOSSSSOO......',
    '...............OOFFOOSSSSSDDPEO.....',
    '..............OFFFFOSSSSSDDEPEOO....',
    '............OOFFFFOOSSSDDDOEEEO.....',
    '..........OOFFFFOOSSSSDDDBBOEOO.....',
    '.........OOFFFOOSSSSDDBBBBBMMMO.....',
    '........OFFFFOOASSDDBBBBBABMMMOO....',
    '........OFFOOSSSSADABBBBBBBMLLHO....',
    '........OOOOSSSDDBBBBBBBBALLLLHO....',
    '.OO.....OOSSSSDDBBBBBMBMLLLLLHHO....',
    'OFOO....OSSSDDBBAABMBMLLLLLLLOO.....',
    '.OFFOO..ODDDDABBBMBMMLLLLLLFFO......',
    '..OOFFOOODDBBBBBBBMLLLLLLLFFFOO.....',
    '...OFFFFOOBBBBABMLLLLLLLOFFFOO......',
    '....OFFFFFOBMBMMLLLLLLLOOOOO........',
    '.....OOFFFOBBMLLLLLLLFO..OO.........',
    '......OFFFFOBMLLLLLFFFFO............',
    '.......OFFFOOBLLLLFFFFOO............',
    '.......OOFFOOOOOOOFFOO..............',
    '........OFFO..OOOOOO................',
    '........OFFO........................',
    '........OFOO........................',
    '.........OFO........................',
    '.........OOO........................',
    '.........OFO........................',
    '.........OO.........................',
  ],
  long: [
    '................................O......',
    '.............................OOOOOO....',
    '...........................OOSSDDEO....',
    '........................O.OSSDDEEEEO...',
    '..................OOO.OOSOSSDDDOEEOO...',
    '.................OOFFOSSSSDDDDBOOEOO...',
    '...............OOFFFFSSSSDBDBBBBMMOO...',
    '...............OFFFOOSSDDBBBBBMMLLOO...',
    '...............OOOOSSDDBBBBBBLLLLHO....',
    '..............OOSSSSDDBBBBBLLLLLLOO....',
    '.............OSSSSDDBBBBBMLLLLLOO......',
    '............OSSSSDBBBBBMLLLLLLFFO......',
    '...........OOSSDDBBBBBMLLLLLOOFFO......',
    '..........OSSDDBBBBBMLLLLLLO.OOO.......',
    '.O........OSDDBBBBMLLLLLLOO...O........',
    'OFOOOOO..OSSBBBBMMLLLLLOO..............',
    '.OOFFFFOOOODBBBMLLLLLLFO...............',
    '..OFFFFFFFFOBMBLLLLLFFFOO..............',
    '...OOFFFFFFOBBLLLLLOOOOO...............',
    '.....OOFFFFOOOLLLOO..OO................',
    '.......OFFFOOOOOO......................',
    '.......OFFFO...........................',
    '.......OFFO............................',
    '.......OFFFO...........................',
    '.......OFFO............................',
    '.......OFFO............................',
    '........OFO............................',
    '.......OFFO............................',
  ],
  oval: [
    '.....................O...............',
    '...................OOAO..............',
    '.................OOAAAOOOOOO.........',
    '................OAAAFFFOSSSSO........',
    '..............OOAAOFFFFSSSSSDOO......',
    '............OOAAOFFFFOOSSSSDDEOO.....',
    '...........OAAOOFFFOOSSDSDDOEEEO.....',
    '..........OAAOFFFFOOSSDDDDDOEEEO.....',
    '...........OAFFFOOSSDDBDDDBBOMOO.....',
    '...........OOFFOOSDDBBBBBBBBMMMO.....',
    '...........OFOOSSDDBBBMBBMMMLLLO.....',
    '..........OSSSSDDBBBBBBMMMLLLLLHO....',
    '.OO......OSSSSDDBBMMBBMMLLLLLLLO.....',
    'OFOOO....OSSDDBBBMBMMMLLLLLLLLHO.....',
    '.OFFFOOO.OSDBBBBBMMMMLLLLLLLLOO......',
    '..OOFFFOOOOBBBBBBMMLLLLLLLLLFFO......',
    '...OFFFFFFOBBBBMBLLLLLLLLLFFFFO......',
    '....OOFFFFFOBMMMLLLLLLLLFFFFOO.......',
    '......OFFFFOOBLLLLLLLLLFFFFOO........',
    '.......OOFFFOBLLLLLLLFFFFOO..........',
    '........OFFFOOBLLLLLFFFOO............',
    '........OFFFOOOOOLOFOOOO.............',
    '........OFFFO.OO.O.O.O...............',
    '.........OFFO........................',
    '.........OFFO........................',
    '.........OFFO........................',
    '.........OOFO........................',
    '..........OO.........................',
    '.........OOFO........................',
    '..........OO.........................',
  ],
  forked: [
    '.............................O.O........',
    '....................OOOO..OOOSOOOO......',
    '..................OOFFFFOOSSSSSSOO......',
    '.................OOFFFFFOSSSSSDDPEO.....',
    '................OFFFFFFOOSDDDDOEEEO.....',
    '...............OFFFFFOOSSDDDDDOOEEO.....',
    '...............OFFFFOSSDDDDDDBBOEOO.....',
    '...............OOOOOSSDDBBBBBBBMMMO.....',
    '...............OSSSSDDBBBBBBBMMLLLLO....',
    '..............OSSSDDBBBBBMBMMLLLLLOO....',
    '.............OSSSDDBBMBMBMMMLLLLLLOO....',
    '............OSSDDBBMBMBBMMLLLLLLHO......',
    '.OO...O.....OOSDBBBMMBMMLLLLLLLHHO......',
    'OFFOOOFOOOOOOODBBBMBMBLLLLLLLLLOO.......',
    '.OFFFFFFFFFFFFOBBBMMMLLLLLLLLFFO........',
    '..OOFFFFFFFFFFOBBMMLLLLLLLLLFFFOO.......',
    '...OOFFFFFFFFFFOBLLLLLLLLLOOFFOO........',
    '.....OOFFFFFFFFOOBLLLLLLLO.OOO..........',
    '.......OOOFFFFFOOOOLLLLOO...O...........',
    '..........OFFFFO.OOOOOO.................',
    '..........OFFFOO........................',
    '.........OFFFFO.........................',
    '.........OFFFFO.........................',
    '.........OFFFFO.........................',
    '.........OFFFO..........................',
    '.........OFFOO..........................',
    '.........OOFO...........................',
    '.........OFFO...........................',
    '.........OOFO...........................',
    '..........OO............................',
  ],
};

// Palette slots: [O outline, S shadow, D dorsal, B body, M midtone,
//                 L belly, H highlight, F fin, A accent]
export const PALETTES = {
  silver:  ['#151b26', '#2d4a63', '#3f6b8a', '#6f9ab5', '#a3c2d4', '#d8e8f0', '#ffffff', '#4e7d9c', '#e8b53c'],
  crimson: ['#2b0f14', '#7d1226', '#a11d33', '#d94257', '#ec7d8e', '#ffd9de', '#fff5f6', '#b8283f', '#ffb703'],
  gold:    ['#2e2208', '#7d5410', '#b07d1a', '#e8b53c', '#f2cf7a', '#fff2cc', '#fffaeb', '#c9911f', '#f26430'],
  ocean:   ['#0b1a28', '#14536b', '#1f6f8b', '#3fa9c9', '#7fcbe0', '#dff3fa', '#ffffff', '#1a7f9c', '#ffd23f'],
  emerald: ['#06180f', '#12563a', '#1f7a4d', '#3fbf7f', '#7ad9a8', '#e0fbee', '#ffffff', '#186842', '#ffd23f'],
  slate:   ['#101218', '#262d38', '#3d4654', '#6f7d92', '#9dabbd', '#e6ebf2', '#ffffff', '#4a5568', '#f26430'],
  sunset:  ['#2a1004', '#8a2c06', '#c2410c', '#f97316', '#fca55d', '#ffe8d1', '#fff7ed', '#d1500e', '#ffd23f'],
  // Cloud tones S->H plus gold F (rim) / A (core). Icons only.
  weather: ['#1b2430', '#5b6b80', '#8496ab', '#aebccd', '#d5e0ea', '#f2f7fb', '#ffffff', '#d99b23', '#ffd23f'],
  violet:  ['#170c24', '#3f1a86', '#5b21b6', '#8b5cf6', '#b192fa', '#efe6ff', '#ffffff', '#6d31c9', '#ffd23f'],
};

const EYE = { E: '#ffffff', P: '#10141c' };

/**
 * Render a sprite grid as an inline SVG string.
 * shape-rendering:crispEdges keeps pixels hard at any scale.
 */
export function renderSprite(grid, paletteKey = 'ocean', { size = 64, className = '', flip = false } = {}) {
  const p = PALETTES[paletteKey] || PALETTES.ocean;
  const map = { O: p[0], S: p[1], D: p[2], B: p[3], M: p[4], L: p[5], H: p[6], F: p[7], A: p[8], ...EYE };
  const h = grid.length;
  const w = grid[0].length;
  let rects = '';

  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const fill = map[grid[y][x]];
      if (fill) rects += `<rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>`;
    }
  }

  const g = flip ? `<g transform="translate(${w},0) scale(-1,1)">${rects}</g>` : rects;
  return `<svg class="pixel ${className}" viewBox="0 0 ${w} ${h}" width="${size}" height="${Math.round((size * h) / w)}" ` +
    `xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges" role="img" aria-hidden="true">${g}</svg>`;
}

/**
 * Small horizontal sprite — species cards, map pins, log thumbnails.
 * Side-on and compact so it stays legible down to ~34px.
 */
export function speciesSprite(species, opts) {
  return renderSprite(SPRITES[species.sprite] || SPRITES.perch, species.palette, opts);
}

/**
 * Large angled "hero" art for the species detail sheet only.
 *
 * Falls back to the horizontal sprite whenever a species has no hero drawn
 * yet, so the set can be filled in gradually without any screen breaking.
 * A species opts in with `hero: '<key>'`; otherwise its `sprite` key is tried
 * against HEROES first.
 */
export function speciesHero(species, opts) {
  const grid = HEROES[species.hero] || HEROES[species.sprite] || SPRITES[species.sprite] || SPRITES.perch;
  return renderSprite(grid, species.palette, opts);
}

/** True when a species has real angled art rather than the fallback. */
export function hasHero(species) {
  return Boolean(HEROES[species.hero] || HEROES[species.sprite]);
}

export function icon(name, opts = {}) {
  const grid = ICONS[name];
  return grid ? renderSprite(grid, opts.palette || 'ocean', opts) : '';
}
