// ---------------------------------------------------------------------------
// PIXEL ART ENGINE
//
// Sprites are plain character grids. Each character maps to a slot in a
// palette, so one shape can be recoloured per species.
//
//   O outline   S shadow (back)   D dorsal    B body     M midtone/dither
//   L belly     H highlight       F fin       A accent
//   E eye white P pupil           . transparent
//
// The M slot is what does the work: dithering M against B and L gives a soft
// gradient down the flank without needing more colours, which is what makes
// these read as shaded rather than flat.
//
// Fish bodies are hand-drawn and their caudal fins generated as an outlined
// forked tail — see tools/author_sprites.py, which emits the block below.
// Edit sprites THERE and regenerate, rather than hand-editing these grids.
// ---------------------------------------------------------------------------

export const SPRITES = {
  deep: [
    '..........OOOOOOOO........OFO',
    '.........OFFFFFFFO........OFO',
    '........OFFFFFFFFFO......OFO.',
    '......OOOFFFFFFFFOOO....OFFO.',
    '....OOSSSOOOOOOOOSSSOO..OFFO.',
    '...OSSSSSSSSSSSSSSSSSO.OFFFO.',
    '..OSSSSSDDDDDDDDDDDDSOOFFFO..',
    '.OSDDDDDDDDBBBBBBBBBDOOFFFO..',
    'OODDDDDBBBBBBBBBBBBBBOFFFFO..',
    'OEPEODDBBBBBBMBMBBBBBOFFFO...',
    'OEEEOBBBBBMBMBMBMBBBBOFFFO...',
    'OOEEOBBMBMBMBMBMBMBBBOFFFO...',
    '.OOMMMMLMLMLMLMLMLMLBOFFFFO..',
    '..OMLLLLLLLLLLLLLLLMBOOFFFO..',
    '..OLLLLLLLLLLLLLLLLLBOOFFFO..',
    '..OHLLLLLLLLLLLLLLLLOO.OFFFO.',
    '..OHHLLLLLLLLLLLLLLOO...OFFO.',
    '...OOHHLLLLLLLLLLOO.....OFFO.',
    '.....OOOFFFFFFOOO........OFO.',
    '.......OFFFFFFO...........OFO',
    '.......OOOOOOOO...........OFO',
  ],
  perch: [
    '............OOOOOOOOO.........OFO',
    '...........OFFFFFFFFO........OFFO',
    '..........OFFFFFFFFFFO.......OFO.',
    '.......OOOOFFFFFFFFFOOO.....OFFO.',
    '....OOOSSSSOOOOOOOOSSSSOO..OFFFO.',
    '..OOSSSSSSSSSSSSSSSSSSSSO.OFFFO..',
    '.OSSSSSSDDDDDDDDDDDDDDDSOOFFFFO..',
    'OODDDDDDDDDDBBBBBBBBBBBDOFFFFO...',
    'OEPEODDDDBBBBBBBBBBBBBBBOFFFFO...',
    'OEEEOBBBBBBBBMBMBMBBBBBBOFFFO....',
    'OOEEOBBBBMBMBMBMBMBMBBBBOFFFFO...',
    '.OOMMMBMBMBMBMBMBMBMBMBBOFFFFO...',
    '..OMMLMLMLMLMLMLMLMLMLMBOOFFFFO..',
    '..OLLLLLLLLLLLLLLLLLLLLBO.OFFFO..',
    '...OHLLLLLLLLLLLLLLLLLLOO..OFFFO.',
    '...OOHHLLLLLLLLLLLLLLLOO....OFFO.',
    '.....OOOFFOOOOFFFFOOOO.......OFO.',
    '.......OFFO...OFFFO..........OFFO',
    '.......OOOO...OOOO............OFO',
  ],
  torpedo: [
    '................OOOO.............OFO',
    '...............OFFFFO...........OFFO',
    '..............OFFFFFO..........OFFO.',
    '........OOOOOOOFFFFOOOO.......OFFFO.',
    '.....OOOSSSSSSSSSSSSSSSOO....OFFFO..',
    '...OOSSSSSSSSSSSSSSSSSSSSO..OFFFFO..',
    '.OOSSDDDDDDDDDDDDDDDDDDDDSOOFFFFO...',
    'OODDDDDDDDDBBBBBBBBBBBBBBDOFFFFFO...',
    'OEPEODDDBBBBBBBBBBBBBBBBBBOFFFFO....',
    'OEEEOBBBBBBMBMBMBMBMBBBBBBOFFFFO....',
    'OOEEOBBMBMBMBMBMBMBMBMBMBBOFFFFFO...',
    '.OOMMMLMLMLMLMLMLMLMLMLMLBOOFFFFO...',
    '..OLLLLLLLLLLLLLLLLLLLLLLBO.OFFFFO..',
    '...OOHLLLLLLLLLLLLLLLLLLLOO..OFFFO..',
    '.....OOOHHLLLLLLLLLLLLLLOO....OFFFO.',
    '........OOOOOFFOOOFFOOOOO......OFFO.',
    '.............OFFO.OFFO..........OFFO',
    '..............OO...OO............OFO',
  ],
  tuna: [
    '...........OOOO....................OFO',
    '..........OFFFFO..................OFFO',
    '.........OFFFFFFO................OFFO.',
    '........OFFFFFFFFO..............OFFFO.',
    '.....OOOOFFFFFFFFOOOO.........OOFFFO..',
    '...OOSSSSOOOOOOOOSSSSSOO.....OFFFFFO..',
    '.OOSSSSSSSSSSSSSSSSSSSSSOO..OFFFFFO...',
    'OODDDDDDDDDDDDDDDDDDDDDDDSOOFFFFFFO...',
    'OEPEODDDDDBBBBBBBBBBBBBBBDAOFFFFFO....',
    'OEEEOBBBBBBBBBBMBMBMBBBBBBAOFFFFO.....',
    'OOEEOBBBBBMBMBMBMBMBMBBBBBAOFFFFFO....',
    '.OOMMMMBMBMBMBMBMBMBMBMBMBAOFFFFFFO...',
    '..OMLLLLLLLLLLLLLLLLLLLLLLBOOFFFFFO...',
    '..OLLLLLLLLLLLLLLLLLLLLLLLOO.OFFFFFO..',
    '..OOHLLLLLLLLLLLLLLLLLLLLAO...OOFFFO..',
    '...OOOHHLLLLLLLLLLLLLLLLAO......OFFFO.',
    '.....OOOOFFFFFOOOOOOOOOO.........OFFO.',
    '........OFFFFFFO..................OFFO',
    '.........OOOOOO....................OFO',
  ],
  grouper: [
    '..........OOOOOOOOOOO.......OFO',
    '.........OFFFFFFFFFFFO......OFO',
    '.......OOOFFFFFFFFFFFFO....OFO.',
    '....OOOSSSOOOOOOOOOOOOOO...OFO.',
    '..OOSSSSSSASSSSASSSSSSSSO.OFFO.',
    '.OSSSSSSSSSSSSSSSSSSSSSDOOFFFO.',
    'OODDDADDDDDDDDADDDDDDDDDOOFFO..',
    'OEPEODDDBBBBABBBBBBBABBBOFFFO..',
    'OEEEOBBBBBBBBBBBABBBBBBBOFFFO..',
    'OOEEOBBABBBBMBMBMBBBABMBOFFFO..',
    '.OOMMMBBBBMBMBMBMBMBMBMBOFFFO..',
    '..OMMLMLALMLMLMLMLALMLMBOOFFO..',
    '..OLLLLLLLLLLLLALLLLLLLBOOFFFO.',
    '..OHLLLLLLLLLLLLLLLLLLLOO.OFFO.',
    '..OOHHLLLLLLLLLLLLLLLLOO...OFO.',
    '....OOOFFFFOOOOFFFFFOOO....OFO.',
    '......OFFFFO..OFFFFFO.......OFO',
    '......OOOOOO..OOOOOO........OFO',
  ],
  long: [
    '..............OOOOOO..............OFO',
    '.............OFFFFFO.............OFO.',
    '..........OOOOFFFFOOOOO.........OFFO.',
    '...OOOOOOOSSSSOOOOSSSSSSOO.....OFFFO.',
    '.OOSSSSSSSSSSSSSSSSSSSSSSSSO..OFFFO..',
    'OODDDDDDDDDDDDDDDDDDDDDDDDDSOOFFFFO..',
    'OEPEODDDDBBBBBBBBBBBBBBBBBBDOFFFFO...',
    'OEEEOBBBBBBBBBBBBBBBBBBBBBBBOFFFO....',
    'OOEEOBMBMBMBMBMBMBMBMBMBMBMBOFFFFO...',
    '.OOMMMLLLLLLLLLLLLLLLLLLLLLBOOFFFFO..',
    '..OLLLLLLLLLLLLLLLLLLLLLLLLOO.OFFFO..',
    '..OOHLLLLLLLLLLLLLLLLLLLLLOO...OFFFO.',
    '....OOOOFFOOOOOOOOFFFOOOOO......OFFO.',
    '.......OFFO......OFFO............OFO.',
    '.......OOOO......OOOO.............OFO',
  ],
  oval: [
    '......A.A.A.A.A.A.A.........OFO',
    '......OAOAOAOAOAOAO.........OFO',
    '.....OOFFFFFFFFFFFOO.......OFO.',
    '...OOOFFFFFFFFFFFFFOOO....OFFO.',
    '..OOSSSOOOOOOOOOOOOSSSOO.OFFFO.',
    '.OSSSSSSSSSSSSSSSSSSSSSO.OFFO..',
    '.OSSSSSDDDDDDDDDDDDDDDDOOFFFO..',
    'OODDDDDDDBBBBBBBBBBBBBBOFFFFO..',
    'OEPEODDDBBBBBBMBMBBBBBBOFFFO...',
    'OEEEOBBBBBMBMBMBMBMBBBBOFFFO...',
    'OOEEOBBMBMBMBMBMBMBMBMBOFFFO...',
    '.OOMMMMLMLMLMLMLMLMLMLBOFFFFO..',
    '..OMLLLLLLLLLLLLLLLLLLBOOFFFO..',
    '..OLLLLLLLLLLLLLLLLLLLBO.OFFO..',
    '..OHLLLLLLLLLLLLLLLLLLOO.OFFFO.',
    '..OOHHLLLLLLLLLLLLLLLOO...OFFO.',
    '....OOOFFFFFFFFFFFFOO......OFO.',
    '......OFFFFFFFFFFOO.........OFO',
    '......OOOOOOOOOOOO..........OFO',
  ],
  forked: [
    '..........OOOOOOO...............OFO',
    '.........OFFFFFFFO.............OFFO',
    '........OFFFFFFFFFO..........OOFFO.',
    '......OOOFFFFFFFFOOO........OFFFFO.',
    '...OOOSSSOOOOOOOOSSSSOO....OFFFFO..',
    '.OOSSSSSSSSSSSSSSSSSSSSO.OOFFFFFO..',
    'OOSSSSDDDDDDDDDDDDDDDDSOOFFFFFFO...',
    'OODDDDDDDDBBBBBBBBBBBBDOFFFFFFO....',
    'OEPEODDDBBBBBBBMBMBBBBBOFFFFFO.....',
    'OEEEOBBBBBBMBMBMBMBMBBBOFFFFFO.....',
    'OOEEOBBMBMBMBMBMBMBMBMBOFFFFFO.....',
    '.OOMMMMLMLMLMLMLMLMLMLBOFFFFFFO....',
    '..OMLLLLLLLLLLLLLLLLLLBOOFFFFFFO...',
    '..OLLLLLLLLLLLLLLLLLLLOO.OOFFFFFO..',
    '..OOHLLLLLLLLLLLLLLLLOO....OFFFFO..',
    '...OOOHHLLLLLLLLLLLLOO......OFFFFO.',
    '.....OOOOFFFOOOOOOOO.........OOFFO.',
    '........OFFFFO.................OFFO',
    '........OOOOOO..................OFO',
  ],
  squid: [
    '........OOOOOO.....',
    '......OOSSAASSOO...',
    '.....OSSAAAAAASO...',
    '....OSSAAAAAAAASO..',
    '...OSBBBBBBBBBBBSO.',
    '...OBBBBBBBBBBBBBO.',
    '..OBBBEPBBBBBBEPBBO',
    '..OBBBEEBBBBBBEEBBO',
    '..OBBBBBBBBBBBBBBBO',
    '..OBMBMBMBMBMBMBMBO',
    '...OMMMMMMMMMMMMMO.',
    '...OLOLOLOLOLOLOLO.',
    '...OL.OL.OL.OL.OLO.',
    '..OL..O...O...O..LO',
    '..O...O...O...O...O',
  ],
  crab: [
    '...OO.............OO...',
    '..OAAO..OOOOOOO..OAAO..',
    '..OAAOOOSSSSSSSOOOAAO..',
    '...OOOSSEPSSSEPSSOOO...',
    '....OSBBBBBBBBBBBBSO...',
    '...OSBBBBBBBBBBBBBBSO..',
    '..OOBBBBBBBBBBBBBBBBOO.',
    '.O.OOBBBBMBMBMBMBBBOO.O',
    '.O..OOMMMMMMMMMMMMOO..O',
    '..O..O.OOOOOOOOOO.O..O.',
    '..O..O..O......O..O..O.',
    '.....O..O......O..O....',
  ],
};

// Icon sprites (non-species) used for section headers and empty states.
export const ICONS = {
  // Twin crests with foam tops over water that darkens with depth.
  wave: [
    '........................',
    '.....HH..........HH.....',
    '....HMMH........HMMH....',
    '...HMLLMH......HMLLMH...',
    '..HMLLLLMH....HMLLLLMH..',
    '.HMLLHHLLMH..HMLLHHLLMH.',
    'HMLLHHHHLLMHHMLLHHHHLLMH',
    'MLLMMMMMMLLMMLLMMMMMMLLM',
    'BBMMMMMMMMBBBBMMMMMMMMBB',
    'DBBBBBBBBBBBBBBBBBBBBBBD',
    'SDDDDDDDDDDDDDDDDDDDDDDS',
    'SSSSSSSSSSSSSSSSSSSSSSSS',
  ],
  hook: [
    '.......OOO........',
    '.......OAO........',
    '.......OAO........',
    '.......OAO........',
    '.....OOOAOOO......',
    '....OAAA.AAAO.....',
    '....OAO...OAO.....',
    '....OAO...OAO.....',
    '.....OAOOOAO......',
    '......OAAAO.......',
    '.......OOO........',
    '..................',
  ],
  // Uses the body ramp (B/M/L) rather than the accent slot, so it takes the
  // colour of whichever palette it is rendered with.
  trophy: [
    '...BBBBBBBBBB.....',
    '..BOOOOOOOOOOB....',
    '.BMOLLLLLLLLOMB...',
    '.BMOLMMMMMMLOMB...',
    '.BMOMMMMMMMMOMB...',
    '..BOMMMMMMMMOB....',
    '...BOMMMMMMOB.....',
    '....BOMMMMOB......',
    '.....BBMMBB.......',
    '.......BB.........',
    '.....BBBBBB.......',
    '...BBBBBBBBBB.....',
  ],
  boat: [
    '.......A..........',
    '.......AA.........',
    '.......AAAA.......',
    '.......AAAAAA.....',
    '.......AA.........',
    '..OOOOOOOOOOOOO...',
    '..OAAAAAAAAAAAO...',
    '...OOOOOOOOOOO....',
    '.MM.MMM.MMM.MMM.MM',
    'BLLBLLLBLLLBLLLBLL',
    '..................',
    '..................',
  ],
  // --- weather -------------------------------------------------------------
  // One icon per condition group, keyed from WMO codes by describeCode() in
  // js/api/weather.js. All 20x14 so they line up in the forecast strip.
  // Render these with the 'silver' palette: H/M give white cloud with grey
  // shading, A the gold sun and bolt, D the blue precipitation.
  sunny: [
    '....................',
    '.........AA.........',
    '...A.....AA.....A...',
    '....A..AAAAAA..A....',
    '......AAAAAAAA......',
    '.....AAAAAAAAAA.....',
    '.AA..AAAAAAAAAA..AA.',
    '.....AAAAAAAAAA.....',
    '......AAAAAAAA......',
    '....A..AAAAAA..A....',
    '...A.....AA.....A...',
    '.........AA.........',
    '....................',
    '....................',
  ],
  // Crescent: convex on the left, concave on the right. Solid, not a ring.
  moon: [
    '....................',
    '.........AAAAA......',
    '..A....AAAAAAA......',
    '......AAAAAAA.......',
    '.....AAAAAA.........',
    '.....AAAAA..........',
    '.A...AAAAA..........',
    '.....AAAAAA.........',
    '......AAAAAAA.......',
    '.......AAAAAAA......',
    '.........AAAAA......',
    '....................',
    '....................',
    '....................',
  ],
  cloudy: [
    '....................',
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOHHHHHHHHHHHOO...',
    '.OHHHHHHHHHHHHHHHO..',
    '.OHHHHHHHHHHHHHHHO..',
    '.OMMHHHHHHHHHHHMMO..',
    '.OMMMMMMMMMMMMMMMO..',
    '..OOOOOOOOOOOOOOO...',
    '....................',
    '....................',
    '....................',
    '....................',
  ],
  partly: [
    '..............AAA...',
    '............AAAAAAA.',
    '...........AAAAAAAA.',
    '.....OOOO..AAAAAAAA.',
    '...OOHHHHOOAAAAAAA..',
    '..OHHHHHHHHOAAAAA...',
    '.OHHHHHHHHHHHO......',
    '.OMMHHHHHHHMMO......',
    '.OMMMMMMMMMMMO......',
    '..OOOOOOOOOOO.......',
    '....................',
    '....................',
    '....................',
    '....................',
  ],
  drizzle: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOHHHHHHHHHHHOO...',
    '.OHHHHHHHHHHHHHHHO..',
    '.OMMHHHHHHHHHHHMMO..',
    '.OMMMMMMMMMMMMMMMO..',
    '..OOOOOOOOOOOOOOO...',
    '....................',
    '....D...D...D.......',
    '....................',
    '...D...D...D........',
    '....................',
    '....................',
  ],
  rain: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOHHHHHHHHHHHOO...',
    '.OHHHHHHHHHHHHHHHO..',
    '.OMMHHHHHHHHHHHMMO..',
    '.OMMMMMMMMMMMMMMMO..',
    '..OOOOOOOOOOOOOOO...',
    '....................',
    '...D...D...D...D....',
    '...D...D...D...D....',
    '....................',
    '..D...D...D...D.....',
    '..D...D...D...D.....',
  ],
  showers: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOHHHHHHHHHHHOO...',
    '.OHHHHHHHHHHHHHHHO..',
    '.OMMHHHHHHHHHHHMMO..',
    '.OMMMMMMMMMMMMMMMO..',
    '..OOOOOOOOOOOOOOO...',
    '....................',
    '..D..D..D..D..D.....',
    '.D..D..D..D..D......',
    '..D..D..D..D..D.....',
    '.D..D..D..D..D......',
    '....................',
  ],
  storm: [
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOHHHHHHHHHHHOO...',
    '.OHHHHHHHHHHHHHHHO..',
    '.OMMHHHHHHHHHHHMMO..',
    '.OMMMMMMMMMMMMMMMO..',
    '..OOOOOOOOOOOOOOO...',
    '..........AAAA......',
    '.........AAAA.......',
    '........AAAA........',
    '......AAAAAAAA......',
    '.........AAA........',
    '........AAA.........',
  ],
  fog: [
    '....................',
    '.......OOOOO........',
    '.....OOHHHHHOO......',
    '....OHHHHHHHHHO.....',
    '..OOHHHHHHHHHHHOO...',
    '.OHHHHHHHHHHHHHHHO..',
    '.OMMHHHHHHHHHHHMMO..',
    '..OOOOOOOOOOOOOOO...',
    '....................',
    '..MMMMMMMMMMMMMM....',
    '....................',
    '.MMMMMMMMMMMMMM.....',
    '....................',
    '..MMMMMMMMMMMM......',
  ],
  book: [
    '..OOOOOOOOOOOOOO..',
    '..OBBBBBBOBBBBBO..',
    '..OBLLLLBOBLLLLO..',
    '..OBLLLLBOBLLLLO..',
    '..OBBBBBBOBBBBBO..',
    '..OBLLLLBOBLLLLO..',
    '..OBLLLLBOBLLLLO..',
    '..OBBBBBBOBBBBBO..',
    '..OOOOOOOOOOOOOO..',
    '..................',
    '..................',
    '..................',
  ],
};

// Palette slots: [O outline, S shadow, D dorsal, B body, M midtone,
//                 L belly, H highlight, F fin, A accent]
export const PALETTES = {
  silver:  ['#151b26', '#2d4a63', '#3f6b8a', '#6f9ab5', '#a3c2d4', '#d8e8f0', '#ffffff', '#4e7d9c', '#e8b53c'],
  crimson: ['#2b0f14', '#7d1226', '#a11d33', '#d94257', '#ec7d8e', '#ffd9de', '#fff5f6', '#b8283f', '#ffb703'],
  gold:    ['#2e2208', '#7d5410', '#b07d1a', '#e8b53c', '#f2cf7a', '#fff2cc', '#fffaeb', '#c9911f', '#f26430'],
  ocean:   ['#0b1a28', '#14536b', '#1f6f8b', '#3fa9c9', '#7fcbe0', '#dff3fa', '#ffffff', '#1a7f9c', '#ffd23f'],
  emerald: ['#06180f', '#12563a', '#1f7a4d', '#3fbf7f', '#7ad9a8', '#e0fbee', '#ffffff', '#186842', '#ffd23f'],
  slate:   ['#101218', '#262d38', '#3d4654', '#6f7d92', '#9dabbd', '#e6ebf2', '#ffffff', '#4a5568', '#f26430'],
  sunset:  ['#2a1004', '#8a2c06', '#c2410c', '#f97316', '#fca55d', '#ffe8d1', '#fff7ed', '#d1500e', '#ffd23f'],
  violet:  ['#170c24', '#3f1a86', '#5b21b6', '#8b5cf6', '#b192fa', '#efe6ff', '#ffffff', '#6d31c9', '#ffd23f'],
};

const EYE = { E: '#ffffff', P: '#10141c' };

/**
 * Render a sprite grid as an inline SVG string.
 * shape-rendering:crispEdges keeps pixels hard at any scale.
 */
export function renderSprite(grid, paletteKey = 'ocean', { size = 64, className = '', flip = false } = {}) {
  const p = PALETTES[paletteKey] || PALETTES.ocean;
  const map = { O: p[0], S: p[1], D: p[2], B: p[3], M: p[4], L: p[5], H: p[6], F: p[7], A: p[8], ...EYE };
  const h = grid.length;
  const w = grid[0].length;
  let rects = '';

  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const fill = map[grid[y][x]];
      if (fill) rects += `<rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>`;
    }
  }

  const g = flip ? `<g transform="translate(${w},0) scale(-1,1)">${rects}</g>` : rects;
  return `<svg class="pixel ${className}" viewBox="0 0 ${w} ${h}" width="${size}" height="${Math.round((size * h) / w)}" ` +
    `xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges" role="img" aria-hidden="true">${g}</svg>`;
}

export function speciesSprite(species, opts) {
  return renderSprite(SPRITES[species.sprite] || SPRITES.perch, species.palette, opts);
}

export function icon(name, opts = {}) {
  const grid = ICONS[name];
  return grid ? renderSprite(grid, opts.palette || 'ocean', opts) : '';
}
